defaults: 
  - data: circles
  - model: ripsnet
  - machine: gpu
  - optimizer: sgd
  - paths: didion

trainer:
  _target_: pytorch_lightning.Trainer
  max_epochs: 100
  val_check_interval: 1.0
  devices: ${machine.devices}
  accelerator: ${machine.accelerator}
  strategy: ${machine.strategy}
  log_every_n_steps: 1
  num_nodes: ${machine.num_nodes}
  precision: ${machine.precision}
  gradient_clip_val: 1


logger: 
  _target_: pytorch_lightning.loggers.WandbLogger
  mode: online
  project: ripsnet
  save_dir: ${paths.logs}/wandb
  name: xp
  log_model: False
  offline: True

seed: 42
cv: 1
log: False